function demoWav(notes){
  const sr=8000,spn=sr,n=notes.length*spn,b=new ArrayBuffer(44+n),v=new DataView(b),w=(o,s)=>[...s].forEach((c,i)=>v.setUint8(o+i,c.charCodeAt(0)));
  w(0,'RIFF');v.setUint32(4,36+n,true);w(8,'WAVE');w(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,sr,true);v.setUint32(28,sr,true);v.setUint16(32,1,true);v.setUint16(34,8,true);w(36,'data');v.setUint32(40,n,true);
  for(let i=0;i<n;i++){const j=Math.min(notes.length-1,Math.floor(i/spn)),q=i%spn,f=notes[j],e=Math.max(0,Math.min(1,q/(sr*.03),(spn-q)/(sr*.12))),t=i/sr,x=(Math.sin(2*Math.PI*f*t)*.65+Math.sin(4*Math.PI*f*t)*.18)*e;v.setUint8(44+i,Math.max(0,Math.min(255,Math.round(128+x*95))))}
  return URL.createObjectURL(new Blob([b],{type:'audio/wav'}));
}
const R2='https://pub-e59b6e32dca34106a263ace064f23dcf.r2.dev',PREFIX='pine-music',MANIFESTS=[`${R2}/${PREFIX}/songs.json`,`${R2}/${PREFIX}/song.json`];
const baseTracks=[
  {title:'夜行列车',artist:'Pine Studio',src:demoWav([261.63,329.63,392,329.63,440,392,329.63,293.66]),cover:'cover-purple',durationLabel:'00:08',genre:'轻音乐'},
  {title:'暖色落日',artist:'Chyan Waves',src:demoWav([440,329.63,392,329.63,293.66,329.63,392,440]),cover:'cover-sunset',durationLabel:'00:08',genre:'流行'},
  {title:'城市灯火',artist:'Pine Studio',src:demoWav([329.63,392,493.88,392,329.63,293.66,329.63,392]),cover:'cover-blue',durationLabel:'00:08',genre:'电子'}
];
function remoteTrack(x,i){if(!x||!x.title||!(x.file||x.src))return null;const v=x.file||x.src,k=v.replace(/^\/+/,''),src=/^https?:\/\//i.test(v)?v:`${R2}/${k.startsWith(PREFIX+'/')?k:PREFIX+'/'+k}`;return{title:x.title,artist:x.artist||'未知歌手',src,cover:x.cover||['cover-purple','cover-sunset','cover-blue'][i%3],durationLabel:x.duration||x.durationLabel||'--:--',genre:x.genre||'云端音乐'}}
async function syncCloud(){for(const url of MANIFESTS){try{const r=await fetch(`${url}?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)continue;const j=await r.json(),a=Array.isArray(j)?j:Array.isArray(j.songs)?j.songs:(j.title?[j]:[]),b=a.map(remoteTrack).filter(Boolean);if(!b.length)continue;tracks=b;index=0;load(0);renderSongs($('#searchInput').value);renderQueue();toast(`已同步 ${tracks.length} 首云端音乐`);return}catch(e){console.warn('Cloud music sync failed',url,e)}}console.warn('No valid cloud music manifest found')}
const playlists=[['流行音乐榜','392.6万','cover-1'],['热歌榜','287.4万','cover-2'],['新歌速递','152.3万','cover-3'],['夜行电子','312.8万','cover-4'],['KTV必点榜','226.7万','cover-5'],['网络热歌榜','185.4万','cover-6']];
const $=s=>document.querySelector(s),audio=$('#audio');let tracks=[...baseTracks],index=0,shuffle=false,repeat=false,liked=false;
const fmt=s=>Number.isFinite(s)?`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`:'00:00';
function toast(msg){const x=$('#toast');x.textContent=msg;x.classList.add('show');clearTimeout(window._t);window._t=setTimeout(()=>x.classList.remove('show'),1800)}
function cover(el,c){[...el.classList].filter(x=>x.startsWith('cover-')).forEach(x=>el.classList.remove(x));el.classList.add(c)}
function load(i,play=false){if(!tracks.length)return;index=(i+tracks.length)%tracks.length;const t=tracks[index];audio.src=t.src;['bottomTitle','sideTitle'].forEach(id=>$('#'+id).textContent=t.title);['bottomArtist','sideArtist'].forEach(id=>$('#'+id).textContent=t.artist);cover($('#bottomCover'),t.cover);cover($('#sideCover'),t.cover);renderQueue();if(play)audio.play().catch(()=>toast('请再次点击播放'))}
function toggle(){audio.paused?audio.play().catch(()=>toast('请再次点击播放')):audio.pause()}
function next(){load(shuffle?Math.floor(Math.random()*tracks.length):index+1,true)}function prev(){load(index-1,true)}
function renderSongs(q=''){const data=tracks.filter(t=>(t.title+t.artist+t.genre).toLowerCase().includes(q.toLowerCase())),g=$('#recommendGrid');g.innerHTML=data.length?data.map(t=>`<article class="recommend-card" data-i="${tracks.indexOf(t)}"><div class="card-cover ${t.cover}"><button class="play-chip">▶</button></div><div class="card-meta"><strong>${t.title}</strong><span>${t.artist} · ${t.genre}</span></div></article>`).join(''):'<div class="empty-state">没有找到匹配的音乐</div>';g.querySelectorAll('.recommend-card').forEach(x=>x.onclick=()=>load(+x.dataset.i,true))}
function renderLists(q=''){const data=playlists.filter(x=>x[0].toLowerCase().includes(q.toLowerCase())),g=$('#playlistGrid');g.innerHTML=data.length?data.map(x=>`<article class="playlist-card"><div class="playlist-cover ${x[2]}"><button class="play-chip">▶</button></div><strong>${x[0]}</strong><span>▷ ${x[1]}</span></article>`).join(''):'<div class="empty-state">没有找到匹配的歌单</div>';g.querySelectorAll('.playlist-card').forEach(x=>x.onclick=()=>{shuffle=true;next();toast('已开始随机播放')})}
function renderQueue(){$('#queueCount').textContent=tracks.length;$('#queueList').innerHTML=tracks.map((t,i)=>`<div class="queue-item ${i===index?'active':''}" data-i="${i}"><span class="queue-index">${i===index?'▮▮':i+1}</span><div><strong>${t.title}</strong><small>${t.artist}</small></div><span class="queue-duration">${t.durationLabel||'--:--'}</span></div>`).join('');document.querySelectorAll('.queue-item').forEach(x=>x.onclick=()=>load(+x.dataset.i,true))}
audio.volume=.72;audio.onplay=audio.onpause=()=>{$('#playBtn').textContent=$('#sidePlay').textContent=audio.paused?'▶':'Ⅱ'};audio.onloadedmetadata=()=>{$('#durationTime').textContent=$('#sideDuration').textContent=fmt(audio.duration)};audio.ontimeupdate=()=>{const p=audio.duration?audio.currentTime/audio.duration*100:0;$('#progressBar').value=p;$('#sideProgressFill').style.width=p+'%';$('#currentTime').textContent=$('#sideCurrent').textContent=fmt(audio.currentTime)};audio.onended=()=>repeat?(audio.currentTime=0,audio.play()):next();
$('#progressBar').oninput=e=>{if(audio.duration)audio.currentTime=e.target.value/100*audio.duration};$('#volumeBar').oninput=e=>audio.volume=+e.target.value;
['#playBtn','#sidePlay'].forEach(s=>$(s).onclick=toggle);['#nextBtn','#sideNext'].forEach(s=>$(s).onclick=next);['#prevBtn','#sidePrev'].forEach(s=>$(s).onclick=prev);$('#heroPlay').onclick=()=>load(0,true);$('#shuffleAll').onclick=()=>{shuffle=true;next();toast('已开启随机播放')};
['#shuffleBtn','#sideShuffle'].forEach(s=>$(s).onclick=()=>{shuffle=!shuffle;['#shuffleBtn','#sideShuffle'].forEach(x=>$(x).style.color=shuffle?'#c4b5fd':'');toast(shuffle?'已开启随机播放':'已关闭随机播放')});['#repeatBtn','#sideRepeat'].forEach(s=>$(s).onclick=()=>{repeat=!repeat;['#repeatBtn','#sideRepeat'].forEach(x=>$(x).style.color=repeat?'#c4b5fd':'');toast(repeat?'已开启单曲循环':'已关闭单曲循环')});
function like(){liked=!liked;$('#bottomHeart').textContent=liked?'♥':'♡';$('#heartBtn').style.color=liked?'#fb7185':'#aab2c1';toast(liked?'已添加到我喜欢':'已取消收藏')}$('#bottomHeart').onclick=$('#heartBtn').onclick=like;
$('#muteBtn').onclick=()=>{audio.muted=!audio.muted;$('#muteBtn').textContent=audio.muted?'×':'◖'};$('#queueToggle').onclick=()=>toast('桌面端右侧为播放列表');$('#clearQueue').onclick=()=>{tracks=[tracks[index]];index=0;renderSongs($('#searchInput').value);renderQueue();toast('已保留当前歌曲')};$('#newPlaylist').onclick=()=>toast('已新建一个空歌单');
$('#searchInput').oninput=e=>{renderSongs(e.target.value);renderLists(e.target.value)};document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchInput').focus()}else if(e.code==='Space'&&document.activeElement.tagName!=='INPUT'){e.preventDefault();toggle()}});
document.querySelectorAll('.main-nav .nav-item').forEach(b=>b.onclick=()=>{document.querySelectorAll('.main-nav .nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');toast('已切换到：'+b.dataset.section)});document.querySelectorAll('#genreTabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#genreTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');toast('流派：'+b.textContent)});
$('#filePicker').onchange=e=>{[...e.target.files].forEach((f,i)=>tracks.push({title:f.name.replace(/\.[^/.]+$/,''),artist:'本地音乐',src:URL.createObjectURL(f),cover:['cover-purple','cover-sunset','cover-blue'][i%3],durationLabel:'本地',genre:'本地音乐'}));renderSongs($('#searchInput').value);renderQueue();toast(`已导入 ${e.target.files.length} 首本地音乐`)};
load(0);renderSongs();renderLists();renderQueue();syncCloud();
